name: 기능 요청
description: 새로운 기능 요청을 위한 양식입니다
title: "[기능]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## 기능 요청 상세 정보

        아래 표를 작성해주세요:

        | 구분 | 번호 | 기능 | 상세 내용 | 시작일자 | 종료일자 | 작업일수 |
        |------|------|------|----------|---------|---------|---------|
        |      |      |      |          |         |         |         |

  - type: textarea
    id: feature-details
    attributes:
      label: 기능 상세 정보
      description: 위 표의 내용을 복사하여 작성해주세요
      placeholder: "| 개발 | 1 | 로그인 기능 | 사용자 인증 시스템 | 2025-03-10 | 2025-03-15 | 5 |"
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: 추가 정보
      description: 이 기능이 필요한 이유나 배경에 대해 설명해주세요
